services:
  - type: web
    name: one-job-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DATABASE_URL
        generateValue: true
        type: database
    autoDeploy: true
    branch: main
    rootDir: .

databases:
  - name: one-job-db
    databaseName: onejob
    plan: free